name: cowlar_task
description: "Cowlar Task"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  intl:

  #State management
  flutter_riverpod: ^2.4.10

  #api 
  http: ^1.2.1

  #dependency injection
  get_it: ^7.7.0

  #routing
  go_router: ^13.2.1

  #ui
  google_fonts:
  flutter_screenutil: ^5.9.0

  #env
  flutter_dotenv: ^5.1.0

  #video player
  youtube_player_flutter: ^9.0.1

  #local storage
  floor: ^1.5.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  floor_generator: ^1.4.2
  build_runner: ^2.1.2


flutter:

  uses-material-design: true

  assets:
    - .env

