name: cowlar_task
description: "Cowlar Task"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  #State management
  flutter_riverpod: ^2.4.10

  #api 
  http: ^1.2.1

  #dependency injection
  get_it: ^7.7.0

  #routing
  go_router: ^13.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

